export const GAME_CONSTANTS: {
  TIME_PER_QUESTION: number;
  BASE_POINTS: number;
  MAX_TIME_BONUS: number;
  MAP_CORRECT_THRESHOLD_KM: number;
} = {
  TIME_PER_QUESTION: 10,
  BASE_POINTS: 100,
  MAX_TIME_BONUS: 50,
  MAP_CORRECT_THRESHOLD_KM: 500,
};
